### ISSUE TITLE
Broken 1.0.9

### ISSUE THREAD

**Issue by illabo** [weitieda/bottom-sheet#19]
Here the param `geometry in:` should be just `geometry:`
https://github.com/weitieda/bottom-sheet/blob/72b1809abaf0c7697f4f3633c619c3f7ceda3415/Sources/BottomSheet/BottomSheet.swift#L73

**Comment by weitieda** [comment]
Thanks for bringing it up. It should be fixed in latest master.

**Comment by illabo** [comment]
Thanks! 
Please also note that increasing the minor instead of patch locks the users with SPM pin set with `upToNextMinor` with the forever broken `1.0.9`. 
<img width="498" alt="Снимок экрана 2022-05-12 в 18 06 36" src="https://user-images.githubusercontent.com/6376785/168107300-e55fe537-efb1-4dd9-a30e-4c7b084bbc41.png">

**Comment by weitieda** [comment]
thanks, that's a good point. I've just deleted the `1.1.0` and created a new `1.0.10` @illabo
