### ISSUE TITLE
Layout with Margin after add Bottom Sheet

### ISSUE THREAD

**Issue by MarcusAdriano** [weitieda/bottom-sheet#5]
Hello authors,

I have a simple cart list. After add Bottom sheet to my project, I have unespected margin:

https://user-images.githubusercontent.com/7614148/109086117-bde08e80-76e9-11eb-9460-9281139417e4.png

Before add BottomSheet:

https://user-images.githubusercontent.com/7614148/109086184-e49ec500-76e9-11eb-8e2f-96dd4b1446cf.png

CartView source code: https://gist.github.com/MarcusAdriano/9affed479cd7b47cbedb5d9d940628aa

**Comment by weitieda** [comment]
Can you try to move `.bottomSheet()` up? like on top of `.navigationTitle()`?

**Comment by MarcusAdriano** [comment]
> Can you try to move `.bottomSheet()` up? like on top of `.navigationTitle()`?

Yes, but nothing changed.

**Comment by MarcusAdriano** [comment]
This [topics](https://stackoverflow.com/questions/56614080/how-to-remove-the-left-and-right-padding-of-a-list-in-swiftui) help to solve the problem. It's about List:

```swift
List {
    Text("Row")
}
.listStyle(PlainListStyle())
```

I've tested your example and on iOS 14.4 Lists are render with padding, but on iOS 13.7 there is no padding.

**Comment by weitieda** [comment]
Fix has been merged to master. Closed.
